# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
      - dev

steps:
# ASP.NET Core
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
  displayName: "Install .NET SDK 3.1.x"

- script: dotnet publish './src/Server/Steeltoe.Server.csproj' --output './publish' --configuration Release --framework netcoreapp3.1 --runtime linux-x64 --self-contained
  displayName: 'Publish Project'

- task: CopyFiles@2
  inputs:
    SourceFolder: './publish'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/publish'
    CleanTargetFolder: true
  displayName: "Stage Project"

- powershell: cp "Dockerfile" "$(Build.ArtifactStagingDirectory)/Dockerfile"
  displayName: "Stage Dockerfile"

- task: CopyFiles@2
  inputs:
    SourceFolder: './deploy/kubernetes'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/kubernetes'
    CleanTargetFolder: true
  displayName: "Stage Kubernetes Manifest"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: "Upload Staging"
