trigger:
  branches:
    include:
      - dev

stages:
  - stage: assemble
    displayName: Assemble
    jobs:
      - job: build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: ShellScript@2
            displayName: Generate Staging Manifest
            inputs:
              scriptPath: ./yttw.sh
              args: >
                -f kubernetes
                -v image_tag=$(Build.BuildId)
                -v hostname=dev.steeltoe.io
                -v dotnet_environment=Staging
                --output-files manifests/staging
          - task: ShellScript@2
            displayName: Generate Production Manifest
            inputs:
              scriptPath: ./yttw.sh
              args: >
                -f kubernetes
                -v image_tag=$(Build.BuildId)
                -v replica_count=2
                -v hostname=steeltoe.io
                -v www_hostname=www.steeltoe.io
                -v dotnet_environment=Production
                --output-files manifests/production
          - task: PublishPipelineArtifact@1
            displayName: Publish Manifests
            inputs:
              targetPath: manifests
              artifactName: manifests

  - stage: deploy
    displayName: Deploy
    dependsOn: assemble
    condition:
      not(eq(variables['build.reason'], 'PullRequest'))
    jobs:
      - job: deploy
        displayName: Deploy
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Docker Build and Push
            inputs:
              command: buildAndPush
              containerRegistry: SteeltoeContainerRegistry
              repository: main-site
              tags: |
                $(Build.BuildId)
                latest
