---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-site
  namespace: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-site
  template:
    metadata:
      labels:
        app: main-site
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: main-site
          image: steeltoe.azurecr.io/main-site
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Staging"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: main-site
  namespace: website
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: main-site
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: main-site
  namespace: website
spec:
  virtualhost:
    fqdn: dev.steeltoe.io
    tls:
      secretName: website-tls
  routes:
  - services:
    - name: main-site
      port: 80
